version: '3.8'
services:
  bitwarden-to-keepass:
    build: .
    command: >
      bash -c '
        python3 bitwarden-to-keepass.py --bw-session `$BW_PATH login --raw || $BW_PATH unlock --raw`'
    volumes:
      - ./exports:/exports
      - 'bw-config:/root/.config/Bitwarden CLI'
    env_file:
      - .env

volumes:
  bw-config:
